### PR TITLE
Updates bays and baymodels responses, updates swaggerFull

### PR DESCRIPTION
**Pull request by annegentle**

### CODE REVIEW

**Comment by annegentle** [comment]
@jamiehannaford here are a few more real examples, wanted to ask before merging in case there'll be conflicts.

**Comment by jamiehannaford** [comment]
Looks great :+1:  I noticed the formatting was off though. Would you mind running this:

```bash
bash ./reformat.bash
```

and pushing the changes? If you run into NPM trouble, no worries I can merge as is.

**Comment by annegentle** [comment]
Odd. I ran it, got `Everything has been reformatted` but git doesn't think there's anything to add to the commit?

**Comment by jamiehannaford** [comment]
hmm I'll have a try now. Thanks for the PR

**Pull request merged**
